language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

sudo: false

# coverall vvv
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mkdir -p build/logs

install:
  - composer require stopsopa/google-spreadsheets-api-extension

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
# coverall ^^^

# notifications:
#    email: false



#matrix:
#    allow_failures:
#        - php: hhvm


#script:
#    - composer dump-autoload
#    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

#https://docs.travis-ci.com/user/languages/php#Dependency-Management-(a.k.a.-vendoring)
#install:
#  - ./bin/ci/install_dependencies.sh
#  - php vendor/vendors.php

#install:
#   - composer require symfony/framework-bundle:${SYMFONY_VERSION}
env:
  global:
    secure: D2OOTKiKotW+cfysrn7HuzzJFVqMPMJ73Z/2U2MgeBkmpqBZdtx7MqCyO40kgylN24FTbB6vVeeNR7szbLfp2BD2SwrBMmIRCCTWo09pUvmOalww38/vK3U5mmDpiX5wOOlQnpkGyzOV/L0PD+M15mkhSmNFb9tNfs5lxvpJEn+i3xjX67hcqPUQsnlvgUTmNx7QCvqDZMPdRkgHC95zEy2wzMNDu+uG3xAoPYiinRhhek1TaTRKIqJxv2K7KDtu34iNncEz3cpavhNnVwodxwi95P80pc+Ko2RKA/nqJEyhHAFksLRVn/ewq5c5hz4x2AwAomlGh6+pTBencouibmREpIGnK8fQ/6GZueHwQuRfz2/aiSMCKl2Hw1+qx++WDWsfVfn3Mv9ZFUnMB6yZ2KTRHvPPE+FmQMbt1IYhGz00BqImQHgtexBvR83MdbfSjIYmGQ5PvE4CWp7ZDbRVAqRGbmUWK33R9JqSDv4Yk8zk4f0quj+kfWKW9G0YeVJodmYQUFL5O0ieAMQBVY6oU9pbdqkprE+lVw9NqYb2Rf21XgizmCf8ieY8bh+x4vHCbnYOT5FdNT+KyPM1eyzQE6sMbqh061oOwMxoKBobuQwJTt5opPXfz3N/QMHNKKJpHJh1djQBzNpBwJIJGXEJO0P1VRIPIlY+oxkQSk3K5NA=

