language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

sudo: false

# coverall vvv
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mkdir -p build/logs

install:
  - composer require stopsopa/google-spreadsheets-api-extension:dev-master

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
# coverall ^^^

# notifications:
#    email: false



#matrix:
#    allow_failures:
#        - php: hhvm


#script:
#    - composer dump-autoload
#    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

#https://docs.travis-ci.com/user/languages/php#Dependency-Management-(a.k.a.-vendoring)
#install:
#  - ./bin/ci/install_dependencies.sh
#  - php vendor/vendors.php

#install:
#   - composer require symfony/framework-bundle:${SYMFONY_VERSION}
env:
  global:
    # var SOMEVAR
   - secure: WZGqW54mPTlV73BS8d65Emp1U133rcH5kfwP1HaJd/rEPm8pcmfvZztLeOhJ15Pb5VGviBFU6NMFadQic/yVNMX+4wBndURbIfyDhRxtes+0aZTDUBAfecF2uoH02MYpZCkQpvhxHfjK2rb2ZoKLceEq794gGsuBBrGyt9aIAEgimJC6p1ZqCawRD23lAGZkzKAHxZskHjelvXW9WWHsGCP8SF0jWBkbK4/9MdVjs9sB2S+N9zyWT/wY20Z4mwudP+bNvtTZ43Y2D+ZC+o1ao++m5hXG5uR1Hwg2er0v3rAb7HPdtt3gOwGiVpxT6guQ9a0sFmvRCzTEAGI6iIUpX7mZ3xko1obEAYdipdJRjzX1i5e80ZyBaT7UZdUDGeG+vpopCGd0h5osk8XIWJNCWLoDdFNGkdhB2CRBvR6465501nWCrImxT6WU6+LdI9JBrn45bVUNhajJP9on5wMnIMvw6msyn8SK8TwtXGnZbEUSymGuOoCGyEu8uAcdQ7U8Nb3p755Qo7WWzumBvPKvdA/iQXOH0COU9dWV/+ZbUnDpqNYNng8uIMgnFj/63DBdlPXagZwllAShKYcZyr5jJf7FWiukRvutbowGge/fpFgsbWZWo7Ps6My64DpEuxb98edx/nvDN5Ee4OB55WNQ9WWdho8QhVXaHZYq8ZrZfps=

